### ISSUE TITLE
Serviceability: build-step modify-yaml & install-knative should print if YAMLFILE not found

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-collection#44]
Pick up result of
https://github.com/appsody/tekton-example/issues/19

**Comment by marikaj123** [comment]
Summary of the work:
The collection defines the pipeline
At the end of the pipeline, it applies YAMLFILE to deploy the application
This YAMLFILE does not exist by default from 'appsody init' and is a file the end user adds to the app repo, or places in a separate repo with a pointer. If the file is not found by the pipeline, there is not a useful message in the log about why it failed.
The issue is related to Serviceability/enhancement.

**Comment by ianpartridge** [comment]
From the description above I don't believe that this will require any changes to the format/structure of the collections themselves?  Rather, the changes will be to the operator/pipeline?

If I am correct, shouldn't this issue be against a different repo?

**Comment by dacleyra** [comment]
My thought is that the bash executed here would be a little more complex and echo a useful message if the `find` fails, so that it is apparent in the logs

https://github.com/kabanero-io/kabanero-collection/blob/master/experimental/java-microprofile-0.2.1/appsody-build-task.yaml#L50

**Comment by kaczyns** [comment]
I think this probably goes to the kabanero-pipelines rep, this file:
https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/tasks/appsody-build-task.yaml

**Comment by groeges** [comment]
Issue moved to [kabanero-io/kabanero-pipelines #57](https://github.com/kabanero-io/kabanero-pipelines/issues/57) via [**ZenHub**](https://www.zenhub.com/)
